//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserInvitation = newUserInvitationTable("public", "user_invitation", "")

type userInvitationTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	Email      postgres.ColumnString
	Status     postgres.ColumnString
	ExpiryTime postgres.ColumnTimestampz
	Token      postgres.ColumnString
	CreateTime postgres.ColumnTimestampz
	UpdateTime postgres.ColumnTimestampz
	Version    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserInvitationTable struct {
	userInvitationTable

	EXCLUDED userInvitationTable
}

// AS creates new UserInvitationTable with assigned alias
func (a UserInvitationTable) AS(alias string) *UserInvitationTable {
	return newUserInvitationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserInvitationTable with assigned schema name
func (a UserInvitationTable) FromSchema(schemaName string) *UserInvitationTable {
	return newUserInvitationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserInvitationTable with assigned table prefix
func (a UserInvitationTable) WithPrefix(prefix string) *UserInvitationTable {
	return newUserInvitationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserInvitationTable with assigned table suffix
func (a UserInvitationTable) WithSuffix(suffix string) *UserInvitationTable {
	return newUserInvitationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserInvitationTable(schemaName, tableName, alias string) *UserInvitationTable {
	return &UserInvitationTable{
		userInvitationTable: newUserInvitationTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newUserInvitationTableImpl("", "excluded", ""),
	}
}

func newUserInvitationTableImpl(schemaName, tableName, alias string) userInvitationTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		EmailColumn      = postgres.StringColumn("email")
		StatusColumn     = postgres.StringColumn("status")
		ExpiryTimeColumn = postgres.TimestampzColumn("expiry_time")
		TokenColumn      = postgres.StringColumn("token")
		CreateTimeColumn = postgres.TimestampzColumn("create_time")
		UpdateTimeColumn = postgres.TimestampzColumn("update_time")
		VersionColumn    = postgres.IntegerColumn("version")
		allColumns       = postgres.ColumnList{IDColumn, EmailColumn, StatusColumn, ExpiryTimeColumn, TokenColumn, CreateTimeColumn, UpdateTimeColumn, VersionColumn}
		mutableColumns   = postgres.ColumnList{EmailColumn, StatusColumn, ExpiryTimeColumn, TokenColumn, CreateTimeColumn, UpdateTimeColumn, VersionColumn}
	)

	return userInvitationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Email:      EmailColumn,
		Status:     StatusColumn,
		ExpiryTime: ExpiryTimeColumn,
		Token:      TokenColumn,
		CreateTime: CreateTimeColumn,
		UpdateTime: UpdateTimeColumn,
		Version:    VersionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
