# https://taskfile.dev

version: '3'

vars:
  COMPOSE_FILE: _dev/db_compose.yml

tasks:
  default:
    cmds:
      - task -l

  up:
    desc: spin up database
    cmds:
      - docker compose -p bigbackend -f {{.COMPOSE_FILE}} up -d

  down:
    desc: shut down database and remove orphans
    cmds:
      - docker compose -p bigbackend down --remove-orphans
