// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package invitation

import (
	entity "github.com/dyxj/bigbackend/internal/sqlgen/bigbackend/public/entity"
	mapx "github.com/dyxj/bigbackend/pkg/mapx"
)

type UserInvitationMapper struct{}

func (c *UserInvitationMapper) CreateRequestToModel(source CreateRequest) UserInvitation {
	var invitationUserInvitation UserInvitation
	invitationUserInvitation.Email = source.Email
	return invitationUserInvitation
}
func (c *UserInvitationMapper) EntityToModel(source entity.UserInvitation) UserInvitation {
	var invitationUserInvitation UserInvitation
	invitationUserInvitation.ID = mapx.MapUUID(source.ID)
	invitationUserInvitation.Email = source.Email
	invitationUserInvitation.StatusRaw = Status(source.Status)
	invitationUserInvitation.ExpiryTime = mapx.MapTime(source.ExpiryTime)
	invitationUserInvitation.Token = source.Token
	invitationUserInvitation.CreateTime = mapx.MapTime(source.CreateTime)
	invitationUserInvitation.UpdateTime = mapx.MapTime(source.UpdateTime)
	invitationUserInvitation.Version = source.Version
	return invitationUserInvitation
}
func (c *UserInvitationMapper) ModelToEntity(source UserInvitation) entity.UserInvitation {
	var entityUserInvitation entity.UserInvitation
	entityUserInvitation.ID = mapx.MapUUID(source.ID)
	entityUserInvitation.Email = source.Email
	entityUserInvitation.Status = string(source.StatusRaw)
	entityUserInvitation.ExpiryTime = mapx.MapTime(source.ExpiryTime)
	entityUserInvitation.Token = source.Token
	entityUserInvitation.CreateTime = mapx.MapTime(source.CreateTime)
	entityUserInvitation.UpdateTime = mapx.MapTime(source.UpdateTime)
	entityUserInvitation.Version = source.Version
	return entityUserInvitation
}
