// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package userprofile

import (
	entity "github.com/dyxj/bigbackend/internal/sqlgen/bigbackend/public/entity"
	mapx "github.com/dyxj/bigbackend/pkg/mapx"
)

type UserProfileMapper struct{}

func (c *UserProfileMapper) EntityToModel(source entity.UserProfile) UserProfile {
	var userprofileUserProfile UserProfile
	userprofileUserProfile.ID = mapx.MapUUID(source.ID)
	userprofileUserProfile.Email = source.Email
	userprofileUserProfile.FirstName = source.FirstName
	userprofileUserProfile.LastName = source.LastName
	userprofileUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	userprofileUserProfile.CreateTime = mapx.MapTime(source.CreateTime)
	userprofileUserProfile.UpdateTime = mapx.MapTime(source.UpdateTime)
	userprofileUserProfile.Version = source.Version
	return userprofileUserProfile
}
func (c *UserProfileMapper) ModelToEntity(source UserProfile) entity.UserProfile {
	var entityUserProfile entity.UserProfile
	entityUserProfile.ID = mapx.MapUUID(source.ID)
	entityUserProfile.Email = source.Email
	entityUserProfile.FirstName = source.FirstName
	entityUserProfile.LastName = source.LastName
	entityUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	entityUserProfile.CreateTime = mapx.MapTime(source.CreateTime)
	entityUserProfile.UpdateTime = mapx.MapTime(source.UpdateTime)
	entityUserProfile.Version = source.Version
	return entityUserProfile
}
