//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package entity

import (
	"github.com/google/uuid"
	"time"
)

type UserInvitation struct {
	ID         uuid.UUID `sql:"primary_key"`
	Email      string
	Status     string
	ExpiryTime time.Time
	Token      string
	CreateTime time.Time
	UpdateTime time.Time
	Version    int32
}
