// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package profile

import (
	entity "github.com/dyxj/bigbackend/internal/sqlgen/bigbackend/public/entity"
	mapx "github.com/dyxj/bigbackend/pkg/mapx"
)

type UserProfileMapper struct{}

func (c *UserProfileMapper) CreateRequestToModel(source CreateRequest) UserProfile {
	var profileUserProfile UserProfile
	profileUserProfile.UserID = mapx.MapUUID(source.UserID)
	profileUserProfile.FirstName = source.FirstName
	profileUserProfile.LastName = source.LastName
	profileUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	return profileUserProfile
}
func (c *UserProfileMapper) EntityToModel(source entity.UserProfile) UserProfile {
	var profileUserProfile UserProfile
	profileUserProfile.ID = mapx.MapUUID(source.ID)
	profileUserProfile.UserID = mapx.MapUUID(source.UserID)
	profileUserProfile.FirstName = source.FirstName
	profileUserProfile.LastName = source.LastName
	profileUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	profileUserProfile.CreateTime = mapx.MapTime(source.CreateTime)
	profileUserProfile.UpdateTime = mapx.MapTime(source.UpdateTime)
	profileUserProfile.Version = source.Version
	return profileUserProfile
}
func (c *UserProfileMapper) ModelToEntity(source UserProfile) entity.UserProfile {
	var entityUserProfile entity.UserProfile
	entityUserProfile.ID = mapx.MapUUID(source.ID)
	entityUserProfile.UserID = mapx.MapUUID(source.UserID)
	entityUserProfile.FirstName = source.FirstName
	entityUserProfile.LastName = source.LastName
	entityUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	entityUserProfile.CreateTime = mapx.MapTime(source.CreateTime)
	entityUserProfile.UpdateTime = mapx.MapTime(source.UpdateTime)
	entityUserProfile.Version = source.Version
	return entityUserProfile
}
func (c *UserProfileMapper) ModelToResponse(source UserProfile) Response {
	var profileResponse Response
	profileResponse.ID = mapx.MapUUID(source.ID)
	profileResponse.UserID = mapx.MapUUID(source.UserID)
	profileResponse.FirstName = source.FirstName
	profileResponse.LastName = source.LastName
	profileResponse.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	profileResponse.CreateTime = mapx.MapTime(source.CreateTime)
	profileResponse.UpdateTime = mapx.MapTime(source.UpdateTime)
	profileResponse.Version = source.Version
	return profileResponse
}
