//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserProfile = newUserProfileTable("public", "user_profile", "")

type userProfileTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Email       postgres.ColumnString
	FirstName   postgres.ColumnString
	LastName    postgres.ColumnString
	DateOfBirth postgres.ColumnDate
	CreateTime  postgres.ColumnTimestampz
	UpdateTime  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserProfileTable struct {
	userProfileTable

	EXCLUDED userProfileTable
}

// AS creates new UserProfileTable with assigned alias
func (a UserProfileTable) AS(alias string) *UserProfileTable {
	return newUserProfileTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserProfileTable with assigned schema name
func (a UserProfileTable) FromSchema(schemaName string) *UserProfileTable {
	return newUserProfileTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserProfileTable with assigned table prefix
func (a UserProfileTable) WithPrefix(prefix string) *UserProfileTable {
	return newUserProfileTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserProfileTable with assigned table suffix
func (a UserProfileTable) WithSuffix(suffix string) *UserProfileTable {
	return newUserProfileTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserProfileTable(schemaName, tableName, alias string) *UserProfileTable {
	return &UserProfileTable{
		userProfileTable: newUserProfileTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newUserProfileTableImpl("", "excluded", ""),
	}
}

func newUserProfileTableImpl(schemaName, tableName, alias string) userProfileTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		EmailColumn       = postgres.StringColumn("email")
		FirstNameColumn   = postgres.StringColumn("first_name")
		LastNameColumn    = postgres.StringColumn("last_name")
		DateOfBirthColumn = postgres.DateColumn("date_of_birth")
		CreateTimeColumn  = postgres.TimestampzColumn("create_time")
		UpdateTimeColumn  = postgres.TimestampzColumn("update_time")
		allColumns        = postgres.ColumnList{IDColumn, EmailColumn, FirstNameColumn, LastNameColumn, DateOfBirthColumn, CreateTimeColumn, UpdateTimeColumn}
		mutableColumns    = postgres.ColumnList{EmailColumn, FirstNameColumn, LastNameColumn, DateOfBirthColumn, CreateTimeColumn, UpdateTimeColumn}
	)

	return userProfileTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Email:       EmailColumn,
		FirstName:   FirstNameColumn,
		LastName:    LastNameColumn,
		DateOfBirth: DateOfBirthColumn,
		CreateTime:  CreateTimeColumn,
		UpdateTime:  UpdateTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
