// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	mapx "github.com/dyxj/bigbackend/internal/mapx"
	entity "github.com/dyxj/bigbackend/internal/sqlgen/user_profile_local/public/entity"
	userprofile "github.com/dyxj/bigbackend/internal/userprofile"
)

type UserProfile struct{}

func (c *UserProfile) ModelToEntity(source userprofile.UserProfile) entity.UserProfile {
	var entityUserProfile entity.UserProfile
	entityUserProfile.ID = mapx.MapUUID(source.ID)
	entityUserProfile.Email = source.Email
	entityUserProfile.FirstName = source.FirstName
	entityUserProfile.LastName = source.LastName
	entityUserProfile.DateOfBirth = mapx.MapDate(source.DateOfBirth)
	entityUserProfile.CreateTime = mapx.MapTime(source.CreateTime)
	entityUserProfile.UpdateTime = mapx.MapTime(source.UpdateTime)
	return entityUserProfile
}
