//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"cloud.google.com/go/civil"
	"github.com/google/uuid"
	"time"
)

type UserProfile struct {
	ID          uuid.UUID `sql:"primary_key"`
	Email       string
	FirstName   string
	LastName    string
	DateOfBirth civil.Date
	CreateTime  time.Time
	UpdateTime  time.Time
}
